### ISSUE TITLE
Prograde thermometer

### ISSUE THREAD

**Issue by darkzbaron** [dapperfu/hacking#2]
Hi there, I am trying to reverse engineer the prograde thermometer but it seems password protected. Any idea about that?

**Comment by dapperfu** [comment]
Try admin/admin in AP mode. I can't find the binary anywhere. Sometimes you can get lucky searching for the file but I don't think I found anything. 

I currently use them as dumb thermometers because the beeper is loud enough.

**Comment by darkzbaron** [comment]
Thanks so much. It works, no luck for finding any useful data from it. I may try to reverse engineer with the aoo. I will keep you posted!
